server:
  port: 8092
spring:
  application:
    name: customer-ntt
  data:
    mongodb:
      uri: mongodb+srv://navlag:Fg3UgAroDl8SDVDt@avsavivd.lfqko.mongodb.net/pmactoob?retryWrites=true&w=majority